### ISSUE TITLE
AttributeError: 'Dropdown' object has no attribute 'select'

### ISSUE THREAD

**Issue by embis2003** [Mangio621/Mangio-RVC-Fork#47]
![image](https://github.com/Mangio621/Mangio-RVC-Fork/assets/59685827/86502756-dc9c-4f18-86d6-3f76e3f6053f)

**Comment by Patchy319** [comment]
I am getting the same error

**Comment by Patchy319** [comment]
Temporary Fix:
Comment out the following code in infer-web.py, then create an "audios" folder.
![image](https://github.com/Mangio621/Mangio-RVC-Fork/assets/20646293/803d428d-4831-4c2c-8ea2-6fd3074e21b4)

Note: auto-detect features do not seem to work without this.

**Comment by NicolasAdrian07** [comment]
Where can i find it?

**Comment by Patchy319** [comment]
> Where can i find it?

This will be in the root direct for local installations. Not sure how collab / gradio installs work
![image](https://github.com/Mangio621/Mangio-RVC-Fork/assets/20646293/7bedf7bc-c0a0-4a7e-b2c3-2238a3a9c525)
then just edit that code to have hashtags in front, to make it commented out, in previous image (line 2119)
and then finally, create a empty audios folder in the same root:
![image](https://github.com/Mangio621/Mangio-RVC-Fork/assets/20646293/fe14020a-1b07-4e80-97dd-69b8a0d8c025)

**Comment by embis2003** [comment]
> > Where can i find it?
> 
> This will be in the root direct for local installations. Not sure how collab / gradio installs work ![image](https://user-images.githubusercontent.com/20646293/255365612-7bedf7bc-c0a0-4a7e-b2c3-2238a3a9c525.png) then just edit that code to have hashtags in front, to make it commented out, in previous image (line 2119) and then finally, create a empty audios folder in the same root: ![image](https://user-images.githubusercontent.com/20646293/255365815-fe14020a-1b07-4e80-97dd-69b8a0d8c025.png)

it didnt work :(

**Comment by blaise-tk** [comment]
With the new update, this problem has been fixed.

**Comment by EdLovecraft** [comment]
> With the new update, this problem has been fixed.
i still have the problem, i have to comment out line 2178 `sid0.select(fn=match_index, inputs=[sid0], outputs=[file_index2, file_index4])`

**Comment by EdLovecraft** [comment]
> With the new update, this problem has been fixed.

i still have the problem, i have to comment out line 2178 `sid0.select(fn=match_index, inputs=[sid0], outputs=[file_index2, file_index4])`

**Comment by PatrickSLU** [comment]
@EdLovecraft thank you mate, this worked perfectly
![image](https://github.com/Mangio621/Mangio-RVC-Fork/assets/136882606/1bcdf986-7794-4f4b-bfb6-030f33933eca)
![image](https://github.com/Mangio621/Mangio-RVC-Fork/assets/136882606/808b7027-3197-40c7-80b2-faad1fda1d15)

**Comment by alexlnkp** [comment]
> Temporary Fix: Comment out the following code in infer-web.py, then create an "audios" folder. ![image](https://user-images.githubusercontent.com/20646293/255364639-803d428d-4831-4c2c-8ea2-6fd3074e21b4.png)
> 
> Note: auto-detect features do not seem to work without this.

Please, do NOT do that.
Author of the changes here. If you experience issues with the `select` method, ugrade your gradio python lib version to be exactly 3.34.0. To do this, in root folder of RVC run this CMD command:
```shell
runtime\python.exe -m pip install -r requirements.txt --upgrade
```
if it still doesn't work, try running this:
```shell
runtime\python.exe -m pip uninstall gradio
runtime\python.exe -m pip install gradio==3.34.0 --upgrade
```

Also, better temporary solution in your case would be to change `select` method to `change`.

**Comment by PatrickSLU** [comment]
hello @alexlnkp,
So I shouldnt comment out the lines of code mentioned? Rather update gradio to 3.34.0?
and replace all the select methods in the infer-web.py to gradio?

**Comment by kalomaze** [comment]
You should update Gradio to match the dependency in requirements.txt
This solves the issue.

**Comment by pauldeepvoodoo** [comment]
I had this issue as well and noticed "sid0.select(fn=match_index, inputs=sid0, outputs=file_index2)"  was commented out in the git clone on my local.  I uncommented that line and it is now working.  I'm not sure why it has been commented in master.
